### PR TITLE
Fix customization comments

### LINKED ISSUE #438: Comments from custom-like items do not appear in Customize
## Description

As title suggests, comments "Customized with leaf in \<leaf--name\> block" do not appear inside Customize interface nor custom file when customization is saved.

I think those lines
```elisp
:custom            `((custom-set-variables ,@(mapcar (lambda (elm) `'(,(car elm) ,(cdr elm) ,(format "Customized with leaf in %s block" leaf--name))) leaf--value)) ,@leaf--body)
:custom*           `((custom-set-variables ,@(mapcar (lambda (elm) `'(,(car elm) ,(cdr elm) ,(format "Customized with leaf in %s block" leaf--name))) leaf--value)) ,@leaf--body)
:pl-custom         `((custom-set-variables ,@(mapcar (lambda (elm) `'(,(car elm) (leaf-handler-auth ,leaf--name ,(car elm) ,(cdr elm)) ,(format "Customized in leaf `%s' from plstore `%s'" leaf--name (symbol-name (cdr elm))))) leaf--value)) ,@leaf--body)
:auth-custom       `((custom-set-variables ,@(mapcar (lambda (elm) `'(,(car elm) (leaf-handler-auth ,leaf--name ,(car elm) ,(cdr elm)) ,(format "Customized in leaf `%s' from plstore `%s'" leaf--name (symbol-name (cdr elm))))) leaf--value)) ,@leaf--body)
:custom-face       `((custom-set-faces     ,@(mapcar (lambda (elm) `'(,(car elm) ,(car (cddr elm)))) leaf--value)) ,@leaf--body)
```
should be replaced with
```elisp
:custom            `((custom-set-variables ,@(mapcar (lambda (elm) `'(,(car elm) ,(cdr elm) nil nil ,(format "Customized with leaf in %s block" leaf--name))) leaf--value)) ,@leaf--body)
:custom*           `((custom-set-variables ,@(mapcar (lambda (elm) `'(,(car elm) ,(cdr elm) nil nil ,(format "Customized with leaf in %s block" leaf--name))) leaf--value)) ,@leaf--body)
:pl-custom         `((custom-set-variables ,@(mapcar (lambda (elm) `'(,(car elm) (leaf-handler-auth ,leaf--name ,(car elm) ,(cdr elm)) nil nil ,(format "Customized in leaf `%s' from plstore `%s'" leaf--name (symbol-name (cdr elm))))) leaf--value)) ,@leaf--body)
:auth-custom       `((custom-set-variables ,@(mapcar (lambda (elm) `'(,(car elm) (leaf-handler-auth ,leaf--name ,(car elm) ,(cdr elm)) nil nil ,(format "Customized in leaf `%s' from plstore `%s'" leaf--name (symbol-name (cdr elm))))) leaf--value)) ,@leaf--body)
:custom-face       `((custom-set-faces     ,@(mapcar (lambda (elm) `'(,(car elm) ,(car (cddr elm)) nil ,(format "Customized with leaf in %s block" leaf--name))) leaf--value)) ,@leaf--body)
```

I can prepare a pull request if you want.

### PR DESCRIPTION
**Pull request by tpadioleau**
## Description

Fixes #438.

## Checklist

- [x] I've read [CONTRIBUTING.org](https://github.com/conao3/leaf.el/blob/master/CONTRIBUTING.org).
  - [x] I've assign FSF.
  - [x] The leaf.el after my changed pass all testcases by `make test`.
  - [x] My changed elisp code byte-compiled cleanly.
  - [x] I've added testcases related to my PR.
  - [x] I've fixed README related the my added testcases.

### CODE REVIEW

**Comment by conao3** [comment]
Thanks!
I remembered that `:custom` should expand `customize-set-variable` instead of `customize-set-variables` like `use-package`.
```elisp
(ppp-macroexpand
 (use-package oj
   :ensure t
   :custom ((oj-compiler-c "clang")
            (oj-compiler-python "cpython")
            (oj-default-online-judge 'atcoder))))
;;=> (progn
;;     (use-package-ensure-elpa 'oj
;;                              '(t)
;;                              'nil)
;;     (customize-set-variable 'oj-compiler-c "clang" "Customized with use-package oj")
;;     (customize-set-variable 'oj-compiler-python "cpython" "Customized with use-package oj")
;;     (customize-set-variable 'oj-default-online-judge 'atcoder "Customized with use-package oj")
;;     (require 'oj nil nil))
```

Do you challenge this issue or not?

**Comment by tpadioleau** [comment]
Is it what you had in mind ?

**Comment by conao3** [comment]
awesome!
Please squash these commits into 1 commit?

**Comment by conao3** [comment]
Good, thanks!

**Pull request merged**
