### PR TITLE
Added support to find the leaf block.

### PR DESCRIPTION
**Pull request by Z572**
## Description
like find-function, but in leaf block.

## Checklist

- [ ] I've read [CONTRIBUTING.org](https://github.com/conao3/leaf.el/blob/master/CONTRIBUTING.org).
  - [x] I've assign FSF.
  - [ ] The leaf.el after my changed pass all testcases by `make test`.
  - [ ] My changed elisp code byte-compiled cleanly.
  - [ ] I've added testcases related to my PR.
  - [ ] I've fixed README related the my added testcases.

### CODE REVIEW

**Comment by conao3** [comment]
Please write documentation on README.org?

**Comment by Z572** [comment]
where should i write?



---Original---

**Comment by conao3** [comment]
Oops, please write documentation README.org and README.md (same contents)

OK, I think it's good to create a new top-level section named `Tips` after `System keywords` like below.
```
- System keywords
    - :leaf-protect keyword
    - :leaf-defer keyword
    - :leaf-autoload keyword
    - :leaf-defun keyword
    - leaf-defvar
- Tips
    - leaf-find feature
      brabra...
```

**Comment by Z572** [comment]
Oops, I’m not careful to click the update branch , how to undo?

**Comment by conao3** [comment]
Sorry for the inactivity!
I tried your feature, this is a **very** useful feature!  I fix some style/situation issues, merge this.

**Pull request merged**
