### PR TITLE
Fix typo (isearch-mode-map)

### PR DESCRIPTION
**Pull request by Nyoho**
## Description

Fix typo (isearch-mode-map)

## Checklist

- [x] I've read [CONTRIBUTING.org](https://github.com/conao3/leaf.el/blob/master/CONTRIBUTING.org).
  - [x] I've assign FSF.
  - [ ] The leaf.el after my changed pass all testcases by `make test`.
  - [ ] My changed elisp code byte-compiled cleanly.
  - [ ] I've added testcases related to my PR.
  - [ ] I've fixed README related the my added testcases.

### CODE REVIEW

**Comment by conao3** [comment]
Good, thanks!
One point, why is this PR a draft? If you'd like to merge it, please undraft it.

**Comment by Nyoho** [comment]
The reason why I leave it a draft is that I have not run the test.

**Comment by Nyoho** [comment]
It's not necessary for document correction though... hehehe

**Comment by conao3** [comment]
lol. Good catch, thanks!

**Comment by Nyoho** [comment]
Thank you for merging!

**Pull request merged**
