### PR TITLE
Correctly eval cdr

### PR DESCRIPTION
**Pull request by d125q**
## Description

Currently,

    (leaf some-mode
      :hook (t . other-mode))

macroexpands to

    (prog1 'some-mode
      (leaf-handler-leaf-protect some-mode
        (autoload #'(cdr elm) "some-mode" nil t)
        (add-hook 'some-mode #'(cdr elm))))

while the expected result is

    (prog1 'some-mode
      (leaf-handler-leaf-protect some-mode
        (autoload #'other-mode "some-mode" nil t)
        (add-hook 'some-mode #'other-mode)))

## Checklist

- [x] I've read [CONTRIBUTING.org](https://github.com/conao3/leaf.el/blob/master/CONTRIBUTING.org).
  - [x] I've assign FSF.
  - [x] The leaf.el after my changed pass all testcases by `make test`.
  - [x] My changed elisp code byte-compiled cleanly.
  - [x] I've added testcases related to my PR.
  - [x] I've fixed README related the my added testcases.

### CODE REVIEW

**Comment by conao3** [comment]
Good catch, Thanks!
However, I cannot accept your PR that has not gone through the copyright process defined by the FSF.
Can you do that for me and this repository?

**Comment by d125q** [comment]
I already have copyright assignment with the FSF.

**Comment by conao3** [comment]
OK. Then, push `Agree` button in CLAassistant.

**Comment by conao3** [comment]
And you need to add a test, please.
You don't need to add a lot, at least add what you wrote in the PR.

**Comment by d125q** [comment]
> OK. Then, push `Agree` button in CLAassistant.

Didn't I already do this?  This is the first time I'm using CLAssistant, sorry.

> And you need to add a test, please.
> You don't need to add a lot, at least add what you wrote in the PR in `cort-deftest-with-macroexpand leaf/hook` block in `leaf-tests.el`.

Will do, thanks!

**Comment by conao3** [comment]
Note: In `leaf-test.el`, because of set `leaf-expand-leaf-protect` to `nil` globally, you may need to remove `leaf-handler-leaf-protect` in testcase.

**Comment by d125q** [comment]
Thank you.  I added a test for my PR.

**Comment by conao3** [comment]
Great!
As proof that this PR is over, please increase the version of leaf-keywords to `v3.3.3` and add your name to the tail of [Contributors section](https://github.com/conao3/leaf.el#contributors) in the README.

**Comment by conao3** [comment]
Great! Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
