### PR TITLE
Bugfix: leaf-keys-bind-keymap*'s error: number of arguments.

### PR DESCRIPTION
**Pull request by meziberry**

### CODE REVIEW

**Comment by conao3** [comment]
Are you sure done FSF copyright assigning process?

**Comment by meziberry** [comment]
Sorry not yet.  let me try it.

**Comment by conao3** [comment]
Yes, no problem. `leaf` is one of `ELPA` package (https://elpa.gnu.org/packages/leaf.html), so every contributor should be done fsf copyright assign process.

**Comment by conao3** [comment]
Any activity on FSF signing process?

**Comment by meziberry** [comment]
I am waiting for the replay from FSF.  it is a little slow.

**Comment by conao3** [comment]
OK, I'll wait for that process.

**Comment by meziberry** [comment]
I have received the assignment signed from FSF.

**Comment by conao3** [comment]
Thanks! 

One point, all contributors are required to work on copyright assignment for FSFF. For maintenance reasons, we are using Bot for this verification. Please sign in with your GitHub account and press the `Agree` button.
(The email address associated with the commit may be different from the one registered in GitHub. Can you please check?)

**Comment by conao3** [comment]
All check green! thanks :tada:

**Pull request merged**
