### PR TITLE
leaf-key-bind-keymap's argument PKG can accept a quoted list. And fix…

### PR DESCRIPTION
**Pull request by meziberry**
… #506

### CODE REVIEW

**Comment by conao3** [comment]
Why are you want to require multiple `pkg`?

**Comment by meziberry** [comment]
If the user binds some commands/maps from several different packages.  It is convenient to do it by `leaf-keys`.  if not required any packages,  just omit this argument.

**Comment by conao3** [comment]
I have to require two packages for one keymap...? Do you have a concrete example?

**Comment by meziberry** [comment]
For example:
```emacs-lisp
(leaf-keys 
 ((package-k-map ("a" . map-from-package-a)
                 ("c" . map-from-package-c))
  (package-f-map ("b" . map-from-package-b)))
 nil 'bind-keymap '(package-a  package-b package-c))
```
There are 3 packages in here: `package-a` `package-b` `package-c` .  
If I can specify BIND-KEYMAP-PKG to `package-a` `package-b` `package-c`  to load them when binding.

I think it is a mistake this feature should belong to `leaf-keys`, rather than `leaf-bind-key-map`.
so this PR is wrong.

**Comment by meziberry** [comment]
I think we should close this PR.  What do you think?

**Comment by conao3** [comment]
OK, I close this.

**Pull request closed without merging**
