### PR TITLE
Now :bind can accept lambda form binding. #322

### PR DESCRIPTION
**Pull request by meziberry**
## Description

Let `:bind` keyword accept lambda form.  #322

### CODE REVIEW

**Comment by conao3** [comment]
wow! really?? thanks!

**Comment by conao3** [comment]
```elisp
[FAILED]  leaf/bind-1
< Tested with :equal >
Expected:
'(prog1 'macrostep
   (unless
       (fboundp 'macrostep-expand)
     (autoload #'macrostep-expand "macrostep" nil t))
   (leaf-handler-package macrostep macrostep nil)
   (leaf-keys
    (("C-c e" . macrostep-expand))))

Given:
(macroexpand-1
 '(leaf macrostep :ensure t :bind
    ("C-c e" . macrostep-expand)))

Returned:
(prog1 'macrostep nil
       (leaf-handler-package macrostep macrostep nil)
       (leaf-keys
	(("C-c e" . macrostep-expand))))
```
And here is test summary
```
===== Run 369 Tests, 282 Expected, 87 Failed,  0 Errored on Emacs-27.1 =====
```

After my commit, that issue is resolved and here is test summary.
```
===== Run 369 Tests, 340 Expected, 29 Failed,  0 Errored on Emacs-27.1 =====
```

Now, this issue remains.
```elisp
[FAILED]  leaf/leaf-keys-dryrun-14
< Tested with :equal >
Expected:
'(((go-mode-map :package go-mode
		((vector 'key-chord 105 106)
		 . undo)
		("C-c C-n" . go-run)
		("C-c ." . go-test-current-test)))
  (undo go-run go-test-current-test))
Given:
(leaf-keys
 (:go-mode-map :package go-mode
	       (((vector 'key-chord 105 106)
		 . undo)
		("C-c C-n" . go-run)
		("C-c ." . go-test-current-test)))
 go-mode)
Returned:
(((:go-mode-map :package go-mode
		(((vector 'key-chord 105 106)
		  . undo)
		 ("C-c C-n" . go-run)
		 ("C-c ." . go-test-current-test))))
 nil)
```

You could see this error in GitHub Actions log and you can run test locally via `make check`.

---

Thanks in advance. This issue (`lambda` function in `:bind` keyword) I had given up on, but thanks to you we are almost there!

**Comment by meziberry** [comment]
I am so sorry,   I didn't notice the `make check` test command.  I should PR  after making every test case pass.
I will check the failed cases.

**Comment by conao3** [comment]
No problem! please check it.

**Comment by meziberry** [comment]
These binding forms:
A:  `(map :package a ("b" .  cmd1) ("c" . cmd2))`
B:  `(map :package a (("b" .  cmd1) ("c" . cmd2)))`

Maybe we should use the `A` form rather than `B`,  what about your opinions?

**Comment by conao3** [comment]
Yes, I like `A` but `leaf` supports both of them.
```elisp
(ppp-macroexpand
 (leaf color-moccur
   :bind (("M-s O" . moccur)
          (:isearch-mode-map
           ("M-o" . isearch-moccur)
           ("M-O" . isearch-moccur-all)))))
;;=> (prog1 'color-moccur
;;     (unless (fboundp 'moccur) (autoload #'moccur "color-moccur" nil t))
;;     (unless (fboundp 'isearch-moccur) (autoload #'isearch-moccur "color-moccur" nil t))
;;     (unless (fboundp 'isearch-moccur-all) (autoload #'isearch-moccur-all "color-moccur" nil t))
;;     (leaf-keys
;;      (("M-s O" . moccur)
;;       (isearch-mode-map :package color-moccur
;;                         ("M-o" . isearch-moccur)
;;                         ("M-O" . isearch-moccur-all)))))

(ppp-macroexpand
 (leaf color-moccur
   :bind (("M-s O" . moccur)
          (:isearch-mode-map
           (("M-o" . isearch-moccur)
            ("M-O" . isearch-moccur-all))))))
;;=> (prog1 'color-moccur
;;     (unless (fboundp 'moccur) (autoload #'moccur "color-moccur" nil t))
;;     (unless (fboundp 'isearch-moccur) (autoload #'isearch-moccur "color-moccur" nil t))
;;     (unless (fboundp 'isearch-moccur-all) (autoload #'isearch-moccur-all "color-moccur" nil t))
;;     (leaf-keys
;;      (("M-s O" . moccur)
;;       (isearch-mode-map :package color-moccur
;;                         ("M-o" . isearch-moccur)
;;                         ("M-O" . isearch-moccur-all)))))
```

**Comment by meziberry** [comment]
All test cases have been passed.  Could it be merged? now.

**Comment by conao3** [comment]
Thanks!
I look into this, but there're another issue on this branch.

---
This sample `leaf`...
```elisp
(leaf color-moccur
  :bind ("M-s O" . (lambda () "color-moccur" (interactive) (color-moccur))))
```
will be...
```elisp
(prog1 'color-moccur
  (leaf-keys
   (("M-s O" lambda nil "color-moccur" (interactive) (color-moccur)))))
```
will be...
```elisp
(prog1 'color-moccur
  (leaf-key "M-s O" (lambda nil "color-moccur" (interactive) (color-moccur))))
```
will be...
```elisp
(prog1 'color-moccur
  (let* ((old (lookup-key global-map (kbd "M-s O")))
         (value `(global-map "M-s O" color-moccur ,(and old (not (numberp old)) old) nil)))
    (leaf-safe-push value leaf-key-bindlist)
    (define-key global-map (kbd "M-s O") 'color-moccur)))    ; Oh, no...
```

---
But I want to below Sexp.
```elisp
(prog1 'color-moccur
  (let* ((old (lookup-key global-map (kbd "M-s O")))
         (value `(global-map "M-s O" *lambda-function* ,(and old (not (numberp old)) old) nil)))
    (leaf-safe-push value leaf-key-bindlist)
    (define-key global-map (kbd "M-s O") (lambda () "color-moccur" (interactive) (color-moccur)))))
```

I already added testcase, so if you pass that testcase, this branch will be more awesome.

**Comment by meziberry** [comment]
I rebase this PR on master.  and add the test case about menu-item.

**Comment by conao3** [comment]
All tests are green! Thanks for your contribution! :tada:

**Pull request merged**
