### PR TITLE
Implemented optional leaf-key-bindlist

### LINKED ISSUE #488: Optional leaf-key-bindlist
## Description

Hi, it would be nice to have the feature of leaf-key-bindlist optional.  Leaf is
very good at byte-compiled configs, since it does not need itself at runtime
after byte-compilation.  The only minor inconvenience is that i does require a
(defvar leaf-key-bindlist nil) at the beginning of a config file to work.  I
wanted to disable this feature, since I don't use it.  I was thinking about a
variable like leaf-expand-minimally.  Should I send a PR?  Thanks!

### PR DESCRIPTION
**Pull request by xFA25E**
## Description
Closes #488

## Checklist

- [X] I've read [CONTRIBUTING.org](https://github.com/conao3/leaf.el/blob/master/CONTRIBUTING.org).
  - [X] I've assign FSF.
  - [X] The leaf.el after my changed pass all testcases by `make test`.
  - [X] My changed elisp code byte-compiled cleanly.
  - [X] I've added testcases related to my PR.
  - [X] I've fixed README related the my added testcases.

### CODE REVIEW

**Comment by conao3** [comment]
Sorry, after I saw your patch, I thought it would be smarter to define my own `push` like `leaf-safe-push` that doesn't cause errors when applied to undefined variables.
You are the one who reported this issue, you have done the tedious work of CLA, do you want to do this work and create another PR?

**Comment by xFA25E** [comment]
Yeah, sure. So, I imagine that `leaf-safe-push` would be a macro that expands into a form that checks if the variable is defined, right?

**Comment by conao3** [comment]
Yes, if the variable is defined, the macro expands just `push`, or is not defined, the macro expands `setq`.

> Also, since it took me so long to finally submit this PR, I want to thank you for your patience :)

No worries, this package is one of ELPA packages, FSF procedure is needed for anyone who contributes to this.

**Comment by xFA25E** [comment]
What about the compile-time? At compile time `leaf-key-bindlist` is always defined. That is the reason why I used a `leaf-enable-key-bindlist` (like in the case of `leaf-expand-minimally`). Otherwise, the expanded form itself should be checking for the existence of `leaf-key-bind-list`

**Comment by xFA25E** [comment]
Okay, I hope that this is what you were meaning to do

**Comment by conao3** [comment]
Yes! thanks! Please click 'Agree' button in [CLA assistant](https://cla-assistant.io/conao3/leaf.el?pullRequest=493) if you've already done FSF assign process.

**Comment by xFA25E** [comment]
Ok, done

**Comment by conao3** [comment]
Thanks! merged. Congrats on your first contribution! :tada:

**Pull request merged**
