### PR TITLE
Complete the leaf-key[*]'s PREDICATE function.

### PR DESCRIPTION
**Pull request by meziberry**
Add the predicate function for leaf-key.

### CODE REVIEW

**Comment by conao3** [comment]
Thanks for pointing out this!
This is just a question, but when would I use this feature?
Anyway, it was not a good thing that what was written in the description was not implemented.

(Just information, this feature in `use-package` via https://github.com/jwiegley/use-package/commit/747c75a033409a371bab92861fb23c60a9462d2a )

**Comment by meziberry** [comment]
I have no idea about this feature.  yet I haven't used it.  I think it may be forgot to implement, according to the docstring.

**Comment by conao3** [comment]
Yes, it is a problem that the functionality described in the docstring is not implemented.
However, since I don't know when we use this feature, I think it would be better to remove the corresponding description from the docstring.

**Comment by meziberry** [comment]
Should this  PR be closed?

**Comment by conao3** [comment]
To be honest, I believe this feature is not useful so I want to just remove docstring relating this feature. Could you send PR?

**Comment by meziberry** [comment]
In #515.  I will fix the related docstring.

**Pull request closed without merging**
