### PR TITLE
fix some action about leaf-keys

### LINKED ISSUE #506: leaf-key-bind-keymap  failed to require 'nil,  when pkg is 'nil
## Description

When using `leaf-keys` to bind-keymap without `:package` keyword.  The result `(require 'nil)` will lead to fail.

## Issue leaf-block
```elisp
(leaf-keys ((map ("a" . cccc))) nil 'bind-keymap nil)
```

## Expected output from macroexpand-1 of the leaf-block
```elisp
(progn (leaf-key "a" cccc 'map))
```

### PR DESCRIPTION
**Pull request by meziberry**
* leaf-key-bind-keymap's argument PKG can accept a quoted list. and
    fix #506.
  * leaf-keys-bind-keymap* bugfix, original had an error : number of arguments.
  * complete the leaf-key[*]'s PREDICATE function.
  * When 'bind-keymap being non-nil, use the BIND-KEYMAP-PKG ranther than :package's value.

### CODE REVIEW

**Comment by meziberry** [comment]
`:bind-keymap` `:bind-keymap*` implicitly require the package,  I  have no idea it is good or not?  Generally  `:require` keyword is sufficient and explicitly.

**Comment by conao3** [comment]
Could you split up the PR to make it easier to review? The patch solves a some problems and is much appreciated.

**Comment by meziberry** [comment]
OK. I will send the PR separately.

**Comment by conao3** [comment]
Thanks!

**Pull request closed without merging**
